# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('href', models.URLField(verbose_name=b'\xe9\x93\xbe\xe6\x8e\xa5')),
                ('status', models.PositiveIntegerField(choices=[(1, b'\xe6\xad\xa3\xe5\xb8\xb8'), (2, b'\xe5\x88\xa0\xe9\x99\xa4')], default=1, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text=b'\xe6\x9d\x83\xe9\x87\x8d\xe8\xb6\x8a\xe9\xab\x98\xe5\xb1\x95\xe7\xa4\xba\xe9\xa1\xba\xe5\xba\x8f\xe7\xba\xa6\xe9\x9d\xa0\xe5\x89\x8d', verbose_name=b'\xe6\x9d\x83\xe9\x87\x8d')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u53cb\u94fe',
                'verbose_name_plural': '\u53cb\u94fe',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('display_type', models.PositiveIntegerField(choices=[(1, b'HTML'), (2, b'\xe6\x9c\x80\xe6\x96\xb0\xe6\x96\x87\xe7\xab\xa0'), (3, b'\xe6\x9c\x80\xe7\x83\xad\xe6\x96\x87\xe7\xab\xa0'), (4, b'\xe6\x9c\x80\xe8\xbf\x91\xe8\xaf\x84\xe8\xae\xba')], default=1, verbose_name=b'\xe5\xb1\x95\xe7\xa4\xba\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('content', models.CharField(blank=True, help_text=b'\xe5\xa6\x82\xe6\x9e\x9c\xe8\xae\xbe\xe7\xbd\xae\xe7\x9a\x84\xe4\xb8\x8d\xe6\x98\xafHTML\xe7\xb1\xbb\xe5\x9e\x8b\xef\xbc\x8c\xe5\x8f\xaf\xe4\xb8\xba\xe7\xa9\xba', max_length=500, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u4fa7\u8fb9\u680f',
                'verbose_name_plural': '\u4fa7\u8fb9\u680f',
            },
        ),
    ]
